// Generated by gencpp from file r2d2/AddTwoInts.msg
// DO NOT EDIT!


#ifndef R2D2_MESSAGE_ADDTWOINTS_H
#define R2D2_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <r2d2/AddTwoIntsRequest.h>
#include <r2d2/AddTwoIntsResponse.h>


namespace r2d2
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace r2d2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::r2d2::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::r2d2::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::r2d2::AddTwoInts > {
  static const char* value()
  {
    return "r2d2/AddTwoInts";
  }

  static const char* value(const ::r2d2::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::r2d2::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::r2d2::AddTwoInts > 
template<>
struct MD5Sum< ::r2d2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::r2d2::AddTwoInts >::value();
  }
  static const char* value(const ::r2d2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::r2d2::AddTwoIntsRequest> should match 
// service_traits::DataType< ::r2d2::AddTwoInts > 
template<>
struct DataType< ::r2d2::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::r2d2::AddTwoInts >::value();
  }
  static const char* value(const ::r2d2::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::r2d2::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::r2d2::AddTwoInts > 
template<>
struct MD5Sum< ::r2d2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::r2d2::AddTwoInts >::value();
  }
  static const char* value(const ::r2d2::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::r2d2::AddTwoIntsResponse> should match 
// service_traits::DataType< ::r2d2::AddTwoInts > 
template<>
struct DataType< ::r2d2::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::r2d2::AddTwoInts >::value();
  }
  static const char* value(const ::r2d2::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // R2D2_MESSAGE_ADDTWOINTS_H
