// Generated by gencpp from file r2d2/Num.msg
// DO NOT EDIT!


#ifndef R2D2_MESSAGE_NUM_H
#define R2D2_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace r2d2
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : msg(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : msg(0)  {
  (void)_alloc;
    }



   typedef int64_t _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::r2d2::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::r2d2::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::r2d2::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::r2d2::Num > NumPtr;
typedef boost::shared_ptr< ::r2d2::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::r2d2::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::r2d2::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace r2d2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['C:/opt/ros/melodic/x64/share/std_msgs/cmake/../msg'], 'r2d2': ['C:/kcl/robotics/ros/catkin_ws/src/r2d2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::r2d2::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r2d2::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r2d2::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r2d2::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r2d2::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r2d2::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::r2d2::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97ee05ea4c4bbaede097b37470a3a7c6";
  }

  static const char* value(const ::r2d2::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97ee05ea4c4bbaedULL;
  static const uint64_t static_value2 = 0xe097b37470a3a7c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::r2d2::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "r2d2/Num";
  }

  static const char* value(const ::r2d2::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::r2d2::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 msg\n"
;
  }

  static const char* value(const ::r2d2::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::r2d2::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::r2d2::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::r2d2::Num_<ContainerAllocator>& v)
  {
    s << indent << "msg: ";
    Printer<int64_t>::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // R2D2_MESSAGE_NUM_H
